global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "api-gateway"
    metrics_path: /metrics
    static_configs:
      - targets: ["api-gateway:8001"]

  - job_name: "auth-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["auth-service:9000"]

  - job_name: "url-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["url-service:9000"]

  - job_name: "redirector-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["redirector-service:9000"]

  - job_name: "analytics-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["analytics-service:9000"]
